const weatherTypes = [
  "No information",
  "Clear Sky",
  "Partly cloudy",
  "Cloudy",
  "Cloudy",
  "High clouds",
  "Showers",
  "Light showers",
  "Heavy showers",
  "Rain",
  "Light rain",
  "Heavy rain",
  "Intermittent rain",
  "Intermittent rain",
  "Intermittent rain",
  "Drizzle",
  "Mist",
  "Fog",
  "Snow",
  "Thunderstorms",
  "Rain and thunderstorms",
  "Hail",
  "Frost",
  "Rain and thunderstorms",
  "Convective clouds",
  "Partly cloudy",
  "Fog",
  "Cloudy",
]

export default weatherTypes
